(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 'table'"
p3
sS'layer'
p4
S'E:\\Programming\\Python\\web2py\\applications\\vote_up\\controllers/default.py'
p5
sS'code'
p6
S'def index():\n    \'\'\'Display a post, its comments, its responses and allow for vote-up\'\'\'\n    posts=db(db.posts).select(db.table.ALL, orderby=(db.posts.votes))\n    return response.render(\'default/index.html\', locals())\n    \ndef new_post():\n    \'\'\'Accept a new post\'\'\'\n    post_id = db.posts.insert(\n        title = request.vars["title"],\n        message = request.vars["message"]\n    )\n    #post = db.posts[post_id]\n    return index()\n    \ndef vote():\n    \'\'\'Add a vote\'\'\'\n    post = db(db.posts.id == request.vars["post"]).select().first()\n    if int(request.vars["up"])==1:  inc=1\n    else:   inc=-1\n    post.update_record(votes=post.votes+inc)\n    return index()\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "E:\\Programming\\Python\\web2py\\gluon\\restricted.py", line 204, in restricted\n    exec ccode in environment\n  File "E:\\Programming\\Python\\web2py\\applications\\vote_up\\controllers/default.py", line 22, in <module>\n  File "E:\\Programming\\Python\\web2py\\gluon\\globals.py", line 172, in <lambda>\n    self._caller = lambda f: f()\n  File "E:\\Programming\\Python\\web2py\\applications\\vote_up\\controllers/default.py", line 3, in index\n    posts=db(db.posts).select(db.table.ALL, orderby=(db.posts.votes))\n  File "E:\\Programming\\Python\\web2py\\gluon\\dal.py", line 5119, in __getattr__\n    return self[key]\n  File "E:\\Programming\\Python\\web2py\\gluon\\dal.py", line 5113, in __getitem__\n    return dict.__getitem__(self, str(key))\nKeyError: \'table\'\n'
p11
s.